### ISSUE TITLE
Please add query filter by dojoId

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/cp-events-service#116]
Please add an option for restriciting the search to a specific dojoId.
It will help searching events for a dojo without the need of parsing 3Mb of data client side.

**Comment by Wardormeur** [comment]
Isn't that what load is for?

**Comment by Wardormeur** [comment]
It should allow it : https://github.com/CoderDojo/cp-events-service/blob/master/lib/list-events.js
Do you have a specific use case where it's not done properly?

**Comment by sandrobonazzola** [comment]
CDBRIANZA_UID="9943615c-232b-431e-bc87-323580d62f20" 
    API_URL="https://zen.coderdojo.com/api/2.0/"
    COMMAND="events/search"
    cat <<EOL >filename.txt
    {
    "query":{
      "dojoId":"${CDBRIANZA_UID}",
      }
    }
    EOL
    curl -d @filename.txt "${API_URL}${COMMAND}" --header "Content-Type:application/json"

Returns:
<h1>Internal Server Error</h1><h2></h2><p></p>

**Comment by Wardormeur** [comment]
Remove the comma after the dojoId ;)
JSON doesn't support extra ending commas ;)

**Comment by sandrobonazzola** [comment]
Oops, you're right, sorry :-) Closing.
