### ISSUE TITLE
403 error accessing applications

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/cp-events-service#176]
Hi,
I'm trying to get a report from zen about applications to our past events.
I'm able to fetch events using events/search on our dojo id but then iterating on the events I've 403 forbidden while accessing https://zen.coderdojo.com:443/api/2.0/events/applications/{event_id}.
I'm Champion of the Dojo so using the web interface I've full access to the applications but with REST API looks like I'm missing permissions. I'm pretty sure it worked in the past so it may be a regression (or maybe previously I could access it due to a bug and now you fixed and there's a different way for getting applications data)
The python code I'm using is:

url = "https://zen.coderdojo.com:443/api/2.0/"
headers = {'Content-type': 'application/json'}

def get_applications_for_event(eventId, cookie):
    response = requests.get(url+'events/applications/{eventId}'.format(
        eventId=eventId,
    ), cookies=cookie, headers=headers)
    if(response.ok):
        return response.json()
    else:
        print("Error happened")
        response.raise_for_status()

and I'm calling get_applications_for_event(eventId, cookie): passing the cookie from the login and the event id of the event that I'm searching applications for.

**Comment by sandrobonazzola** [comment]
Maybe this can help: https://zen.coderdojo.com/api/2.0/users/init-user-types
shows:
[
  {
    "title": "Parent/Guardian",
    "name": "parent-guardian"
  },
  {
    "title": "Mentor/Volunteer",
    "name": "mentor"
  },
  {
    "title": "Youth Over 13",
    "name": "attendee-o13"
  },
  {
    "title": "Youth Under 13",
    "name": "attendee-u13"
  },
  {
    "title": "Champion",
    "name": "champion"
  }
]

but despit I'm champion for the dojo I'm looking to, I see my user from https://zen.coderdojo.com/api/2.0/users/instance has: "initUserType": "{\"title\":\"Mentor/Volunteer\",\"name\":\"mentor\"}",

**Comment by Wardormeur** [comment]
Hi Sandro,
Could you specify an event for which it happens? I mostly want to know to which dojo the event belongs so that i can check your permissions on said dojo.

**Comment by sandrobonazzola** [comment]
Hi @Wardormeur , dojo is CoderDojo Brianza, 9943615c-232b-431e-bc87-323580d62f20 .
It happens on all the events from the dojo.
Example:
https://zen.coderdojo.com:443/api/2.0/events/applications/1b60bd31-2ffc-4855-bd55-8673872ed738

**Comment by Wardormeur** [comment]
Hey
We don't use that endpoint anymore for .. reasons. 
I've found the issue related to your perm and issued a PR (https://github.com/CoderDojo/cp-events-service/pull/177) 
As soon as that get deployed, this should be resolved

**Comment by glenpike** [comment]
Closing as flagged as fixed in #177
